# -*- coding: utf-8 -*-
"""Minstack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x1hdhaqNEa4063QkejDZkgdcmKM9ZCem
"""

class MinStack:

    def __init__(self):
        """
        initialize your data structure here.
        """
        
        self.stack = []
        self.min = float('inf')
        self.stack.append(float('inf'))
  
        

    def push(self, x: int) -> None:
        
        if (x <= self.min):
            self.stack.append(self.min)
            self.stack.append(x)
            self.min = x
        else:
            self.stack.append(x)

        #TC : O(1)
        


    def pop(self) -> None:
        
        x = self.stack.pop()
        if(x == self.min):
            self.min = self.stack.pop()

        #TC : O(1)
            
    

    def top(self) -> int:
        
        return self.stack[-1]
        #TC: O(1)

    def getMin(self) -> int:
        return self.min

        #TC : O(1)


#SC:O(N)        
   



# Your MinStack object will be instantiated and called as such:
# obj = MinStack()
# obj.push(x)
# obj.pop()
# param_3 = obj.top()
# param_4 = obj.getMin()