# -*- coding: utf-8 -*-
"""MinStack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPRcfHL5iO4sQA7apVj6JkERw6NLDxpB
"""
class MinStack:

    def __init__(self, size):
        self.stack=[]
        self.minval= float('inf')

    def push(self, val: int) -> None:
        if (val <= self.minval):
          self.stack.append(self.minval)
          self.minval=val
        self.stack.append(val)

    def pop(self) -> None:
        if(self.stack and self.stack.pop()==self.minval): 
          self.minval=self.stack.pop() 

    def top(self) -> int:
        return self.stack[-1]

    def getMin(self) -> int:
        return self.minval
    
      
m = MinStack(15)
m.push(-3)
m.push(5)
m.push(1)
print(m.getMin())
m.pop()
print(m.top())
m.push(10)
print(m.top())
m.push(-5)
print(m.getMin())
